### ISSUE TITLE
Incorrect env name MYSQL_ROOT_PASSWORD

### ISSUE THREAD

**Issue by janishorsts** [responsivecraft/dockerised-mysql-monitoring#2]
In general, we should not advice users to use root password, but a MySQL user with permission to read status variables.

Please rename to MYSQL_PASSWORD in docker-compose.yml.

**Comment by kaaposc** [comment]
Right. It's an artifact left over from mysql docker image that needed a root password to create a database.

**Comment by janishorsts** [comment]
MYSQL_ROOT_PASSWORD is assigned MYSQL_PASSWORD in collectd conf in docker-compose.yml. Should assign MYSQL_PASSWORD.
